/* eslint-disable no-irregular-whitespace */
/*
 * update by zhangwenqi
 * -------------------------------------------------
 * 依赖于 langen - 英语语言配置
 */

// 语言配置,按模块命名，每个模块开始需要有个注释
const language = {
  // 展览展期管理
  ExtensionLang: {
    view: 'View',
    exhibitionManagment: 'Exhibition rollover management',
    exhibitionAreaManagment: 'Exhibition plan settings',
    exhibitionVenueManagement: 'Exhibition Venue Management',
    boothPriceSetting: 'Booth price setting',
    zonePlan: 'Special zone plan',
    zonePlanPreset: 'Special zone plan preset',
    zonePlanSetting: 'Special zone plan settings',
    zonePlanReview: 'Special zone plan review',
    exhibitionAreaPlan: 'Exhibition plan',
    exhibitionAreaCode: 'Exhibition Area',
    hall: 'The pavilion',
    exphall: 'Showroom',
    floor: 'floor',
    area: 'area',
    long: 'length',
    height: 'height',
    wide: 'width',
    exhibitionArea: 'Exhibition area',
    exhibitionType: 'exhibition type',
    exhibitionHallType: 'Showroom type',
    selectFirstHall: 'Please select the pavilion first',
    selectFirstFloor: 'Please select the floor first',
    exhibitionPeriod: 'Exhibition Exhibition',
    exhibitionAreaLayout: 'Exhibition layout',
    boothNumScale: 'The total size of booths in the exhibition area())',
    boothNumScale1: 'Total number of booths',
    brandBoothNum: 'Number of brand booths',
    generalBoothNum: 'The number of general booths',
    arrangeExhibitionTypeCode: 'Layout type',
    arrangeExhibitionOrg: 'Exhibition Contractor',
    applicationWay: 'application route',
    detailHistoryCodes: 'History Zone',
    isNewTheme: 'Is it a new theme area',
    isImportant: 'Do you focus on the area',
    isAllow: 'Do you allow companies to apply for special booths',
    selectedExhibitionAreaColor: 'zone color (click to select)',
    specialAreaColor: 'zone color',
    exhibitionOrg: 'Group organizer',
    numArrangeOrg: 'number of booths arranged by unit',
    positionArrangeOrg: 'Booth position arrangement unit',
    remark: 'Remarks (application route)',
    norm: 'Specification',
    color: 'color',
    standardBoothScale: 'Standard Booth Specifications',
    applicationTypeCode: 'application type',
    isNewThemeArea: 'Is it a new theme exhibition area',
    isImportantArea: 'Do you focus on the exhibition area',
    addPlanDetail: 'Add a plan detail',
    planDetail: 'plan detail',
    languageType: 'version number',
    exhibitionName: 'Exhibition name',
    name: 'name',
    exhibitionNum: 'Duewell',
    exhibitionYear: 'Year',
    exhibitionSeason: 'Quarter',
    exhibitionPeriodCode: 'Extension',
    exhibitionDate: 'Holding time',
    exhibition: 'Exhibition',
    themeName: 'exhibition theme',
    categoryCode: 'Exhibition big class',
    exhibitionRegion: 'The pavilion area',
    exhibitionAreaName: 'Exhibition name',
    zoneAreaName: ' Zone Name',
    numberBooths: 'number of booths',
    priceBoothFee: 'The price of the current booth fee',
    indoorExhibitionHall: 'Indoor showroom',
    outdoorExhibitionHall: 'Outdoor showroom',
    centralAreaZoneA: 'A central channel',
    benchmarkBoothFee: 'base booth fee unit price',
    isNeedDeposit: 'Do you need to pay a deposit',
    depositRate: 'Deposit ratio',
    discountObj: 'Promotional object',
    discountRate: 'Promotion ratio',
    depositPrice: 'deposit price unit',
    depositTime: 'Deposit payment time limit',
    newPriceDetails: 'Add price details',
    boothPriceDetails: 'Booth price details',
    newProgramDetails: 'Add new program details',
    zonePlandetails: 'Special zone plan details',
    zoneCode: 'Zone code',
    zoneChineseName: 'Special Chinese name',
    zoneEnglishName: 'Special zone English name',
    indoorBoothPrice: 'In-room booth price at the moment',
    outdoorBoothPrice: 'Outdoor booth price',
    centralChannelBoothPrice: 'Central Channel Booth at the current price',
    indoorBoothBenchmarkPrice: 'Indoor booth benchmark price',
    outdoorBoothBenchmarkPrice: 'outdoor booth benchmark price',
    centralChannelBoothBenchmarkPrice: 'Central Channel Booth Benchmark Price',
    collectDepositType: 'receive deposit type of exhibition',
    isBenchmarkboothprice: 'whether to use the benchmark booth price',
    deposit: 'Do you need a deposit',
    involvesFine: 'Does it involve a fine?',
    applyForCompanyName: 'Apply for business name',
    applicationAreaName: 'application area name',
    applicationAreaCode: 'application area code',
    applyTime: 'application time',
    addAssociation: 'Add association',
    unrelatedRecord: 'unrelated record',
    zoneName: 'zone name',
    schemeName: 'program name',
    schemeStatus: 'schema status',
    status: 'status',
    selected: 'Selected',
    unSelected: 'not selected',
    haveSelected: 'Selected',
    session: 'session',
    delete: 'delete',
    query: 'Query',
    reset: 'reset',
    add: 'add',
    add1: 'Add',
    edit: 'Modify',
    edit1: 'Edit',
    copy: 'copy',
    save: 'save',
    viewAssociation: 'View association',
    viewAssociatedRecords: 'View associated records',
    createDate: 'create time',
    curtainTime: 'start time',
    closingTime: 'closing time',
    prepareStartTime: 'preparation start time',
    prepareEndTime: 'finish end time',
    dismantleStartTime: 'Distraction start time',
    dismantleEndTime: 'extraction end time',
    time: 'time',
    year: 'year',
    confirm: 'determine',
    cancel: 'Cancel',
    return: 'back',
    yes: 'yes',
    no: 'No',
    creatorName: 'creator',
    operation: 'operation',
    selectPlaceholder: 'Please select',
    inputPlaceholder: 'Please enter',
    spring: 'Spring',
    autumn: 'Autumn',
    positiveIntege: 'positive integer',
    nonNegativeNumberMaxNorm: 'Please enter a non-negative number, the decimal place cannot exceed 3  digits',
    maxInteger10MaxDecimal2: 'The integer part is less than 10 digits, and the decimal place cannot exceed 2 digits',
    percentMaxDecimal2: 'Please enter a percentage of 0-100, up to two decimals',
    maxChar255: 'up to 255 characters',
    maxChar100: 'up to 100 characters',
    maxChar200: 'up to 200 characters',
    maxChar32: 'up to 32 characters',
    addline: 'Add line',
    tips: 'prompt',
    deleteCode: 'Are you sure to delete the rollover? ',
    deleteConfirm: 'Are you sure to delete? ',
    changeStatus: 'Are you sure you want to change the status of the program?',
    addData: 'Please add a complete data first',
    adddifferentData: 'Do not add data repeatedly',
    saveSuccess: 'Data saved successfully',
    overDicMaxNum: 'Exceeded the maximum number of extensions set by the extension dictionary',
    handlePreData: 'Please handle unfinished data first',
    addPreCategoryCode: 'Please increase the exhibition category first',
    inputMaxNorm: 'Please enter a similar format of 3x3, up to three decimal places after the number',
    deleteSussess: 'Data deleted successfully',
    success: 'Operation succeeded',
    faild: 'Operation failed',
    statusSuccessfully: 'The status of the program has been modified successfully',
    undelete: 'Canceled delete',
    canceledChanges: 'Canceled changes',
    dataDelete: 'Please select the data to delete',
    boothPrice: 'The price of the indoor booth, the current price of the outdoor booth, the current price of the central channel booth, at least one parameter is required',
    boothBenchmarkPrice: 'Indoor booth benchmark price, outdoor booth benchmark price,  central  channel    booth benchmark price at least one parameter required',
    depositTrue: 'Whether the deposit selection is required, the deposit type, deposit ratio, deposit unit price, and deposit payment time limit parameters are required',
    needDepositIsTrue: 'When the deposit selection is required, the deposit type and the deposit payment time limit are required, the deposit ratio and the deposit unit price are filled in (or fully filled)',
    alreadyExist: 'Exhibition major categories, regions, exhibition areas already exist',
    dataCannotBeEmpty: 'Data cannot be empty, please add at least one data',
    preset: 'preset',
    setting: 'set',
    audited: 'reviewed',
    inputValidator: 'Please enter a code consisting of English letters, numbers, and underscores, and cannot begin with an underscore',
    inputChinese: 'Please enter Chinese',
    inputEnglish: 'Please enter English',
    lessThanTenthousand: 'Please enter a positive integer of 10,000 or less (including 10,000)',
    lessThanTwentythousand: 'Please enter a positive integer of 20,000 or less (including 20,000)',
    lessThanHundredthousand: 'Please enter a positive integer of 100,000 or less (including 100,000)',
    lessThanTwoHundredthousand: 'Please enter a positive integer of 200,000 or less (including 200,000)',
    zoneCodeAlreadyExists: 'The zone code already exists',
    zoneChineseNameAlreadyExists: 'Special Chinese name already exists',
    zoneEnglishNameAlreadyExists: 'The zone English name already exists',
    chooseFirstTime: 'Please select first',
    choose: 'selected',
    haschoose: 'selected',
    hasnow: 'whether the current session',
    hasyes: 'yes',
    hasno: 'no',
    choosetip: 'Select this session for the current session',
    choosenew: 'This session is the current session',
    isUnifyArrange: 'Whether it is a unified exhibition area',
    isUnifyArrangeSpecialArea: 'Whether it is a unified exhibition area',
    seatArea: 'Booth area',
    common: [],
    repeat: 'The phase and extension of the selected zone plan already exist',
    enterFirstBoothNumScale: 'Please enter the total number of booths first',
    enterFirstSeatArea: 'Please enter the booth area first',
    selectFirstExhibitionAreaCode: 'Please select the name of the exhibition area first',
    notGreaterthan: 'The number of brand booths cannot be larger than the total number of booths',
    notEqualTo: 'Standard booth booth specifications need to match the booth area',
    boothsNotGreaterthan: 'The total number of booths cannot be larger than ',
    brandNotGreaterthan: 'The number of brand booths cannot be greater than',
    generalNotGreaterthan: 'The number of general booths cannot be greater than',
    remainder: 'remaining',
    zoneAreaLayout: 'Zone layout',
    applicationStatus: 'application status',
    timePerNode: 'Each node time cannot be less than the time of each node above the node and can not be greater than the time of each node below the node',
    moreThanStartPreparation: 'The start time of the plot should be less than the time of each node below',
    moreThanEndPreparation: 'The end time of the plan should be greater than the time of each node above and less than the time of each node below',
    moreThanStartTime: 'The start time should be greater than the time of each node above and less than the time of each node below',
    moreThanCloseTime: 'The closing time should be greater than the time of each node above and less than the time of each node below',
    moreThanDismantlingStartTime: 'The start time of the distraction should be greater than the time of each node above and less than the time of each node below',
    moreThanDismantlingEndTime: 'The end of the disassembly should be greater than the time of all nodes above',
    isSpace: 'Cannot start with a space',
    noMatch: 'The current highlighted area does not match the data for the selected session and the exhibition plan under the extension',
    matchingUnit: 'The arrangement unit of the currently highlighted data does not match the selected scheme data of the selected session and extension',
    selectAll: 'All options',
    isAlreadyExist: 'The length and width of the input already exist',
    rolename: 'role name'
  },

  // 底图制作
  BaseMapLang: {
    audit: 'Basemap review',
    view: 'bottom view',
    mapname: 'basemap name',
    version: 'version number',
    hall: 'The pavilion',
    floor: 'floor',
    posts: 'Number of pillars',
    exphall: 'Showroom',
    time: 'Draw time',
    staff: 'Draw a person',
    state: 'state',
    default: 'Default basemap',
    special: 'Showroom type',
    long: 'long',
    wide: 'wide',
    area: 'area',
    down: 'drawing download',
    opinion: 'Audit opinion',
    date: 'time',
    depart: 'department',
    auditor: 'auditor',
    node: 'node',
    operation: 'operation',
    subtype: 'audit status',
    explain: 'Description',
    rolename: 'role name',
    inquiry: 'Opinions and consultations department',
    manage: 'bottom map management',
    confirm: 'determine',
    cancel: 'Cancel',
    delete: 'delete',
    query: 'Query',
    reset: 'reset',
    submit: 'submit',
    recall: 'Withdraw',
    download: 'Download',
    dwgdown: 'DWG download',
    svgdown: 'SVG download',
    pdfdown: 'PDF download',
    isshow: 'display history version',
    startdate: 'start time',
    enddate: 'end time',
    accredit: 'authorization',
    consult: 'Request for advice',
    approval: 'Approval',
    downfiles: 'Bulk download',
    unaudited: 'Not submitted',
    beaudited: 'Pending review',
    auditfail: 'Audit failed',
    auditpass: 'Audit passed',
    withdrawn: 'retracted',
    flag: 'audit',
    falgpass: 'pass',
    falgredo: 'Reject',
    reviewComment: 'Review suggestions',
    common: [],
    testcon: {
      Testname: 'name',
      Testsex: 'gender'
    }
  },
  // 公共国际化
  CommonLang: {
    baseInfo: 'Basic information',
    creatorName: 'creator',
    modifierName: 'Modify person',
    modifyDate: 'modify time',
    creatorDate: 'creation time',
    startDate: 'start time',
    endDate: 'end time',
    add: 'add',
    add1: 'add',
    edit: 'Modify',
    edit1: 'edit',
    save: 'save',
    saveAndClose: 'save & close',
    detaiInfo: 'detai Info',
    view: 'View',
    confirm: 'OK',
    cancel: 'cancel',
    close: 'close',
    delete: 'delete',
    query: 'query',
    reset: 'reset',
    yes: 'Yes',
    no: 'No',
    activation: 'Activate',
    activationSuccess: 'Activation succeeded',
    activationFail: 'activation failed',
    submit: 'submit',
    tips: 'tips',
    operation: 'operation',
    operationSuccess: 'Operation succeeded',
    operationFail: 'Operation failed',
    deleteSuccess: 'delete successfully',
    cancelDelete: 'Canceled deletion',
    confirmDeletionAllSelect: 'Are you sure you want to delete the selected data?',
    normal: 'Normal',
    remark: 'remarks',
    disconnected: 'disabled',
    input: 'Please enter',
    select: 'Please select',
    selectData: 'Please select data',
    selectOneData: 'Can only select one piece of data',
    selectOneLeast: 'Please select at least one',
    lengthIn: 'length is in',
    lengthMustGt: 'The length must be greater than',
    lengthMustLt: 'The length must be less than',
    between: 'to',
    character: 'characters',
    max10: 'The length cannot exceed 10 characters',
    max16: 'The length cannot exceed 16 characters',
    max32: 'The length cannot exceed 32 characters',
    max50: 'The length cannot exceed 50 characters',
    cencalConfirm: 'The form has been modified, are you sure you want to close the window?',
    selectLeftTree: 'Please select a piece of data from the dictionary tree on the left',
    confirmDelete: 'Are you sure you want to delete the selected data?',
    logoutConfirm: 'Are you sure you want to login out system?',
    handleUnfinishedData: 'Please process unfinished data first',
    nameValidator: 'Cannot contain special characters',
    nameValidator2: 'The name can only contain letters, numbers, underscores, Chinese characters, and cannot contain special characters',
    passwordValidator: 'The password consists of English letters, numbers, and _ and cannot begin with _',
    accountValidator: 'The account consists of English letters, numbers, @, and _ and cannot begin with @ or _',
    plzEnterCorrectEmail: 'Please enter the correct email address',
    emailValidator: 'Please enter the correct email address in the format xx@xx.xx',
    mobileValidator: 'Please enter the correct phone number',
    globalMobileValidator: 'Please enter the correct domestic mobile number or international numbe',
    numberValidator: 'Please enter a valid numeric value',
    message: 'This field is required',
    moreselect: 'Can only select data that is approved for review and pending review',
    export: 'export',
    accountInfo: 'Account info',
    changePassword: 'Modify password',
    findPwd: 'Retrieve password ',
    revisePhoneNum: 'Modify Phone number ',
    getEmail: 'Send email',
    reviseEmail: 'Modify email'
  },
  // 模板图制作
  TemplateMapLang: {
    audit: 'template diagram review',
    tplapproval: 'template map approval',
    view: 'Template view view',
    review: 'view',
    mapname: 'template map name',
    version: 'version number',
    hall: 'The pavilion',
    floor: 'floor',
    pavilienRegion: 'area',
    statistical: 'Statistical method (standard booth size)',
    boothNum: 'Showroom booth number',
    hasDiverse: 'Is there a standard booth (not a 3x3 booth, not an island)',
    main: 'main channel width',
    subsidiary: 'the number of sub-master channels',
    island: 'Is there an island type',
    approvalStatus: 'Approval status',
    posts: 'Number of pillars',
    exphall: 'Showroom',
    time: 'Draw time',
    staff: 'Draw a person',
    buttomGraphStatus: 'basemap state',
    buttomGraphVersion: 'basemap version',
    buttomGraphName: 'basemap name',
    state: 'state',
    long: 'long',
    wide: 'wide',
    area: 'area',
    down: 'drawing download',
    batchDownload: 'Bulk download',
    demand: 'required',
    node: 'node',
    opinion: 'Audit opinion',
    date: 'time',
    depart: 'department',
    authorize: 'audit',
    auditor: 'auditor',
    reviewtime: 'audit time',
    operation: 'operation',
    explain: 'Description',
    authorization: 'Exhibition Authorization',
    rolename: 'role name',
    departname: 'department name',
    inquiry: 'Opinions and consultations department',
    manage: 'template map management',
    confirm: 'determine',
    cancel: 'Cancel',
    delete: 'delete',
    have: '有',
    no: 'No',
    pass: 'pass',
    fail: 'Do not pass',
    query: 'Query',
    reset: 'reset',
    submit: 'submit',
    recall: 'Withdraw',
    download: 'Download',
    look: 'View',
    startdate: 'start time',
    enddate: 'end time',
    selectdown: 'Select download format',
    dwgdown: 'DWG download',
    svgdown: 'SVG download',
    pdfdown: 'PDF download',
    isshow: 'display history version',
    accredit: 'authorization',
    consult: 'Request for advice',
    viewApproval: 'View/Approval',
    selectPlaceholder: 'Please select',
    inputPlaceholder: 'Please enter',
    unsubmitted: 'uncommitted',
    pendingReview: 'Pending review',
    auditNotPassed: 'Audit does not pass',
    auditPassed: 'Audit passed',
    withdrawn: 'retracted',
    reject: 'Reject',
    tips: 'prompt',
    onlySelectedSuccess: 'Only select the data in the audit pass status',
    pleaseSelectedSuccess: 'Please select the data in the audit pass status',
    selectedNeedData: 'Please select the data you want to download first',
    retractData: 'Are you sure you want to withdraw the selected data? ',
    withdrawSuccessfully: 'Withdraw successfully',
    cancelledWithdrawal: 'Cancelled withdrawal',
    submitSelectedData: 'Are you sure you want to submit? ',
    submittedSuccessfully: 'Submit successfully',
    submissionFailed: 'Submit failed',
    cancelledSubmission: 'Canceled submission',
    increaseRoleName: 'Please increase the role name first',
    dataSavedSuccessfully: 'Data saved successfully',
    repeatedAddition: 'Do not add repeatedly',
    increaseDepartment: 'Please add department first',
    confirmDelete: 'Are you sure to delete? ',
    notApproved: 'When the audit item is not approved, the audit result cannot be selected through ',
    isRejected: 'When the audit result is rejected, the review comments are required'
  },

  // 方案图制作
  PlanMapLang: {
    audit: 'scheme diagram review',
    view: 'schema view',
    mapname: 'program name',
    version: 'version number',
    hall: 'the pavilion',
    floor: 'floor',
    areacode: 'exhibition area',
    statis: 'statistics',
    exphall: 'showroom',
    expnum: 'the number of years',
    expcode: 'number of periods',
    stand: 'standard booth size',
    boothnum: 'exhibition space',
    areanum: 'exhibition booth number',
    isprostand: 'atypical standard booth',
    mainwidth: 'main channel width',
    mainnum: 'number of primary and secondary channels',
    island: 'Is there an island type?',
    state: 'schema diagram review status',
    isbase: 'Whether to use the base map',
    istemp: 'Whether to use the template map',
    basestate: 'basemap audit status',
    tempstate: 'template review status',
    time: 'draw time',
    staff: 'draw a person',
    default: 'default scheme map',
    special: 'showroom type',
    long: 'long',
    wide: 'wide',
    area: 'area',
    down: 'drawing download',
    opinion: 'audit opinion',
    date: 'time',
    depart: 'department',
    auditor: 'auditor',
    node: 'node',
    operation: 'operation',
    subtype: 'audit status',
    explain: 'description',
    rolename: 'role name',
    inquiry: 'opinions and consultations department',
    manage: 'scheme management',
    confirm: 'determine',
    cancel: 'cancel',
    next: 'next',
    pubilsh: 'publish',
    delete: 'delete',
    query: 'query',
    reset: 'reset',
    submit: 'submit',
    recall: 'withdraw',
    download: 'download',
    dwgdown: 'dwg download',
    svgdown: 'svg download',
    pdfdown: 'pdf download',
    pngdown: 'png download',
    isshow: 'display history version',
    startdate: 'start time',
    enddate: 'end time',
    choose: 'selected release',
    accredit: 'authorization',
    consult: 'request for advice',
    demand: 'required',
    approval: 'approval',
    authorize: 'audit',
    reviewtime: 'audit time',
    pass: 'pass',
    fail: 'do not pass',
    isselect: 'whether to release or not',
    historytitle: 'history frame map list',
    schemegraph: 'scheme map',
    boothnumber: 'booth number',
    inputarea: 'please enter the name of the exhibition area',
    batchDownload: 'bulk download',
    schemegroup: 'program group',
    selectexpcode: 'select extension',
    inputcontent: 'please enter the content',
    select: 'please select',
    input: 'please enter',
    maxChar255: 'up to 255 characters',
    boothscale: 'booth size',
    status: 'state',
    progress: 'progress',
    calculating: 'in calculation',
    completed: 'completed',
    schemegroupresult: 'generating scheme',
    schemegroupname: 'scheme group name',
    scheme: 'scheme',
    boothtotal: 'total number of booths',
    schemegroupadd: 'add a scenario group',
    selectexphall: 'select the showroom',
    add: 'add',
    viewgroup: 'view',
    selectData: 'please check the data first',
    saveSuccess: 'data saved successfully',
    schemeOne: 'scenario 1',
    schemeTwo: 'scenario 2',
    schemeThree: 'scenario 3',
    rulePositive: 'a positive integer within 11 digits',
    downfiles: 'bulk download',
    unaudited: 'Not submitted',
    beaudited: 'Audit',
    auditfail: 'Audit failed',
    auditpass: 'Audit pass',
    withdrawn: 'Withdrawn',
    waitaudit: 'To be consulted',
    flag: 'To examine',
    falgpass: 'adopt',
    falgredo: 'refuse',
    reviewComment: 'Audit suggestion',
    unchoose: 'Unpublished',
    haschoose: 'Published',
    maptrue: 'yes',
    mapfalse: 'no',
    exhibitionNum: 'Session',
    exhibitionPeriodCode: 'Extension',
    common: []
  },

  // 组织机构国际化
  SysDepartmentLang: {
    moduleName: 'Organization management',
    dialogName: 'Organization information',
    tradingGroupRegion: 'Subtradegroup region',
    version: 'version number',
    deptCode: 'Department code',
    deptName: 'Department name',
    fullName: 'Department fullName',
    tradeGroupCode: 'Subtradegroup code',
    tradeGroupName: 'Subtradegroup name',
    tradeGroupFullName: 'Subtradegroup fullName',
    parentName: 'Parent department',
    deptType: 'Department type',
    typeBloc: 'bloc',
    typeCompany: 'company',
    state: 'status',
    stateActive: 'Enable',
    stateDisable: 'Disable',
    remark: 'remark',
    createDate: 'Creation time',
    selectPlaceholder: 'please select',
    plzSelectParent: "Can't add, please choose the parent department",
    add: 'add',
    operation: 'operation',
    cancel: 'cancel',
    delete: 'delete',
    query: 'query',
    reset: 'reset',
    submit: 'submit',
    recall: 'recall',
    deptAddr: 'Department address',
    contactsInfo: 'Contact information',
    contacts: 'Contact',
    email: 'email',
    postcode: 'postcode',
    fax: 'fax'
  },

  //字典国际化
  DictLang: {
    dataManager: 'Data dictionary management',
    info: 'dictionary info',
    name: 'dictionary name',
    code: 'dictionary code',
    type: 'dictionary type',
    state: 'dictionary state',
    orderNo: 'dictionary orderNo',
    parentDict: 'parent dictionary name',
    languageType: 'language type',
    languageContent: 'language content',
    putOrderNo: 'Please enter a dictionary orderNo',
    putName: 'Please enter a dictionary name',
    putCode: 'Please enter a dictionary code',
    putParentDict: 'Please enter a parent dictionary name',
    putLanguageContent: 'Please enter the language content',
    putLanguageType: 'Please enter the language type',
    nameDuplication: 'Duplicate dictionary name!',
    codeDuplication: 'Duplicate dictionary code!',
    parentDictIsNull: 'Parent dictionary is empty!'
  },
  //角色权限国家
  RoleLang: {
    manage: 'role permission management',
    name: 'role name',
    menuPermission: 'menu permission'
  },

  //用户国际化
  UserLang: {
    name: 'name',
    userName: 'username',
    account: 'account',
    roleName: 'role',
    workDept: 'department',
    userState: 'user status',
    assoRoles: 'associated role',
    mobile: 'Mobile phone',
    email: 'email',
    resetPassword: 'reset password',
    state: 'status',
    effective: 'effective'
  },

  // 位置安排
  LocationLang: {
    view: 'location arrangement',
    programName: 'Scenario Name:',
    programNameTable: 'Scenario Name',
    onlineArrange: 'Arrange an enterprise online',
    onlineLabel: 'Online Arrangement',
    automaticArrange: 'automatic arrangement',
    downloadExcel: 'Download Excel template',
    viewProgress: 'View progress',
    schemeComparison: 'Scheme comparison',
    import: 'import',
    downloadPDF: 'Download and generate PDF files',
    publicity: 'publicity',
    publish: 'publication',
    sessionnumber: 'number',
    exhibitionPeriod: 'Extension:',
    exhibitionPeriodTable: 'extension',
    exhibitionAreaName: 'Exhibition name:',
    exhibitionAreaNameTable: 'extension area name',
    exhibitionProperty: 'Nature of booth:',
    exhibitionPropertyTable: 'Nature of booth',
    creatorName: 'program creator',
    createDate: 'Scenario creation time',
    modifierName: 'program modifier',
    modifyDate: 'scheme modification time',
    description: 'scenario status',
    approvalPerson: 'Pending reviewer',
    publicityTime: 'publication time',
    publicityStatus: 'publication status',
    startDate: 'start date',
    endDate: 'end date',
    publishTime: 'Publish time',
    publishStatus: 'Publish Status',
    revoke: 'undo',
    revokeMsg: 'Do you want to revoke the program?',
    releasePublish: 'release announcement',
    iImmediatePublish: 'Instant Release:',
    publishBatch: 'Publish Batch:',
    timingPublish: 'Timed announcement:',
    publishExplain: 'Publishing instructions:',
    publicityDeadline: 'Publicity deadline:',
    publicityExplain: 'publication instructions',
    releasePublicity: 'release publicity',
    exhibitionNumber: 'Number of exhibitions:',
    exhibitionArea: 'Exhibition:',
    exhibitionAreaTable: 'exhibition area',
    selectFile: 'Select File',
    specialArea: 'Special Zone:',
    drawArrange: 'According to the lottery number of the trading group:',
    exhibitionPositionSame: 'The same number of booths:',
    exhibitionPositionNum: 'by booth number:',
    specialAreaArrange: 'Booth number by exhibition area/special area:',
    outsourceReview: 'outsourcing review',
    workReview: 'Working Department Review',
    foreignPartReview: 'Foreign Trade Division Review',
    foreignReview: 'Patch Scheme Foreign Trade Division Review',
    workPartReview: 'Patch Solution Work Department Review',
    smallToBig: 'From small to large',
    bigToSmall: 'From big to small',
    programCode: 'Canton Fair Code',
    random: 'random',
    highToLow: 'High to low',
    lowToHigh: 'low to high',
    seatCheckLabel: 'Check if the location arrangement meets the location rules',
    violationRuleType: 'Violation of the arrangement rule type',
    ruleType: 'rule type',
    checkResult: 'Check result',
    forceReason: 'Forced to submit reasons for explanation',
    upload: 'Upload',
    exhibitionAreaTip: 'Please select the exhibition area',
    programNameTip: 'Please enter a scheme name',
    exhibitionPositionTypeTip: 'Please select the booth type',
    publishTips: 'fill in the specific requirements for the modification',
    batchMsg: 'Please select the batch to post',
    toLongMsg: 'The length cannot exceed 255 characters',
    publishMsg: 'Publish success',
    startDateTips: 'Please select the start date',
    startDateMsg: 'The start date cannot be greater than the end date',
    endDateTips: 'Please select the end date',
    endDateMsg: 'End date cannot be less than start date',
    publicityMsg: 'public success',
    approvalMsg: 'Please select review comments',
    approvalCommentMsg: 'Please enter an audit opinion',
    longMsg: 'The length cannot exceed 200 characters',
    selectFileMsg: 'Please select file',
    importMsg: 'Imported successfully',
    sessionTips: 'Please select the number of exhibitions',
    exhibitionTips: 'Please select extension',
    exhibitionPropertyTips: 'Please select the nature of the booth',
    specialAreaTips: 'Please select a zone',
    workPartSum: 'Collection of work department audit results',
    autoArrangTips: 'Please set the corresponding rules in the rule settings',
    cancelSucess: 'Undo success',
    exhibitsArea: 'Exhibition Area',
    reviewScore: 'Review score',
    boothArea: 'Booth area',
    mainCampProduct: 'Main product',
    arrangeNum: 'arrange the number',
    exhibitionAreaType: 'The nature of the exhibition area',
    booth: 'Booth',
    startCompared: 'Begin contrast',
    exhibitionHall: 'Showroom',
    floor: 'floor',
    score: 'Brand score is higher than the main sub-channel location business name',
    showInfo: 'Show booth information',
    createTable: 'generate list',
    distribution: 'assignment',
    arrangeSubmitTips: 'Please arrange at least one booth to save or submit! ',
    exhibition: 'Exhibition',
    recommendedNum: 'Booth recommendation number',
    arrangementNum: 'arranged booth number',
    progressStatus: 'progress status',
    proportion: 'The percentage of booths has been arranged',
    progressSum: 'Booth position scheduling schedule',
    numSum: 'Booth position arrangement quantity statistics table',
    contrastExport: 'contrast export',
    contrastExportTips: 'Please compare and then export the scheme',
    exportCode: 'Booth code',
    reomveArrange: 'Remove Arrangement',
    specialArealabel: 'Special booth arrangement situation',
    passwaywaylabel: 'Main and secondary channel arrangement situation',
    mainProductlabel: 'Main product distribution',
    secondLevellabel: 'Secondary exhibit distribution',
    businessLabel: 'Transaction group booth distribution',
    selectTypeLabel: 'Select booth type',
    breakRules: 'Business violation rules',
    noAccordCode: 'There are no eligible booths',
    selectCodeTips: 'Please select the booth first and then operate',
    removeCodeTips: 'Please select the booth to be removed before proceeding',
    codeRepeat: 'The booth arrangement is repeated',
    brand: 'brand',
    generalSpecial: 'General special installation',
    generalStandard: 'general standard booth',
    total: 'total',
    extensionNum: 'number of periods',
    mainPageLabel: 'Location scheduling plan summary',
    orderBusiness: 'trading group',
    lookUpDrawing: 'Find drawings',
    orderCompany: 'company name',
    on: '',
    contentTitle: 'th Publication of Location Arrangement Scheme for Special Exhibitions in Canton Fair',
    explain: 'Canton Fair booth map description: ',
    firstContent: 'The specific location of each exhibiting company on the drawing may be partially modified. All exhibitors are required to use the booth number notified by the trading group. ',
    downloadAndSet: 'You need to download and install ',
    browse: ' before you can browse the PDF file. ',
    firstPart: 'First period',
    secondPart: 'Second period',
    thirdPart: 'The third period',
    businessTips: 'Please select a trading group',
    companyTips: 'Please enter company name',
    introduce: 'Introduction:',
    session: 'Number of times:',
    updateTime: 'Update:',
    drawingType: 'drawing type:',
    fileSize: 'file size:',
    companyLabel: 'Find booth drawings by company',
    companyName: 'company name',
    companyPartTips: 'Hint: Click on the company name to view the detailed booth drawing',
    mergeDownload: 'Merge download',
    businessPartTips: 'Tips: If you choose to use the "Merge Download" function, the downloaded drawing file is large, and may be slower due to factors such as the network. Please wait patiently for the browser to respond. ',
    pageTips: 'The booth drawing',
    businessPageTips: 'Tradeplace Booth Drawing',
    explainReason: 'Description reason:',
    checkIngTips: 'Please fill in the comments',
    expcode: 'number of periods',
    arrangeTime: 'schedule time',
    afterBoothCode: 'Adjusted booth number',
    arrangeReson: 'Arrange the reason',
    arrangeResonForm: 'Arrange the reason:',
    arrangeResonTips: 'Please enter the reason for the arrangement',
    explainReasonTips: 'Please enter the reason',
    enterpriseCode: 'Enterprise Code',
    centralChannel: 'Do you have a central channel:',
    centralChannelTable: 'whether the central channel',
    onlineArrangeTips: "The selected booth number is greater than the recommended number of booths, can't be assigned",
    isEnd: 'whether done',
    saveAs: 'Save as',
    saveAsLabel: 'Save as program name',
    currentInfo: 'current plan',
    historyInfo: 'contrast scheme',
    exhibitionNumberTable: 'The number of exhibitions',
    contrastInfo: 'Contrast scheme information',
    centralChannelInfo: 'Please select whether or not the central channel information',
    passagewayTable: 'Main and secondary channel arrangement list',
    programCodeLabel: 'Canton Fair Code:',
    reappraisal: 'Please upload relevant documents for enterprise Reevaluation',
    help: 'Help',
    helTitle: 'Plug-in diagram operation instructions',
    tipsOne: '1. Click on any blank booth area in the map to arrange enterprise information for this location area; press Ctrl to select multiple booth locations for unified scheduling. ',
    tipsTwo: '2. For the arranged booths, if there are unreasonable arrangements, you can select the post and click to remove the arrangement, delete the arrangement information, and reschedule the new location. ',
    tipsThree: '3. Hold down Ctrl + scroll the mouse scroll to zoom in and out of the plugin image; hold down Alt + mouse to drag and drop the plugin image. ',
    tipsFourth: '4. The gray inoperable part of the area does not belong to the currently selected area of the exhibition area, so the booth operation cannot be performed. ',
    importFail: 'Import failed, please confirm that the import template is correct! ',
    reappraisalFial: 'Enterprise re-evaluation related file import failed, please check and re-import! '
  },
  //规则设置
  RuleSettingLang: {
    firstView: 'Standard adjustment range authorization',
    secondView: 'rule prompt',
    thirdView: 'pre-arranged business',
    thirdAddTitle: 'Add new pre-arranged business',
    lastView: 'Import the lottery result',
    enterpriseName: 'company name:',
    enterpriseNameTable: 'business name',
    exhibitionPositionType: 'Booth type:',
    exhibitionPositionTypeTable: 'Booth type',
    authorizedContent: 'authorized content',
    addAuthorized: 'Add Authorized Enterprise',
    remove: 'remove',
    businessDelegationName: 'Trade name:',
    businessDelegationNameTable: 'transaction group name',
    drawNumber: 'lot number:',
    drawNumberTable: 'lot number',
    arrangeRuleTitle: 'Arranging rule prompts',
    arrangeRuleTips: 'Arrange rules prompt content:',
    tips: 'Only upload Excel files',
    exhibitionPositionNumber: 'Booth number',
    allDelete: 'Bulk delete',
    ruleTip: 'Please read carefully and check ',
    enterpriseNameTips: 'Please enter the company name',
    warrantDialogTips: 'Please select at least one company',
    warrantRemoveTips: 'Do you want to remove the enterprise standard adjustment scope authorization? ',
    removeSuccessTips: 'Remove successfully',
    businessDelegationNameTips: 'Please enter the name of the trading group',
    drawNumberTips: 'Please enter the lottery number',
    deleteAllMsg: 'Do you want to delete in bulk? ',
    hintContentTips: 'Please enter the rules for scheduling rules',
    positionNumberTips: 'Please enter the booth number',
    selectOneTips: 'Please select a company',
    removeMsg: 'Do you want to remove the business? ',
    ruleSetTitle: 'Automatically arrange rule settings',
    selectOneMsg: 'Please select one',
    ruleSetTips: 'Automatically arrange rules',
    saveSuccess: 'Save successfully'
  },
  //查看进度
  CheckProgress: {
    view: 'Check the progress of the schedule',
    businessDelegation: 'transaction group',
    relevantCommerceChamber: 'Related Commerce Chamber',
    recommendTotal: 'Recommended total',
    arrangeNumber: 'arranged number',
    progress: 'progress',
    filterGranularity: 'Filter granularity',
    businessDelegationTips: 'Please enter the trading group information',
    filterGranularityTips: 'Please select filter granularity'
  },
  //展位调整申请
  AdjustmentApply: {
    view: 'Booth adjustment application',
    exhibitionType: 'Layout type:',
    exhibitionTypeTable: 'Layout Type',
    adjustmentNumber: 'Adjustment quantity:',
    adjustmentNumberTable: 'Adjust quantity',
    adjustmentContent: 'Adjust content:',
    adjustmentContentTable: 'Adjust content',
    annex: 'Attachment:',
    annexTable: 'attachment',
    applyTime: 'application time',
    earnestMode: 'Whether the deposit mode is enabled:',
    boothCode: 'Booth number:',
    businessName: 'Exchange location trading group name:',
    adjuestReson: 'Adjustment reason:',
    adjuestResonTable: 'Adjust the reason',
    uploadAnnex: 'Upload attachment:',
    download: 'Download',
    uploadBtn: 'Click upload',
    tipMsg: 'The paid deposit of the booth has not been returned',
    applyBtn: 'Apply',
    backBtn: 'return',
    postionArrange: 'Arrange location',
    subtype: 'Audit status:',
    subtypeTable: 'Audit Status',
    subtypeTips: 'Please select the audit status',
    businessReview: 'Business Association Review',
    refuse: 'Reject',
    refuseReson: 'Reject reason',
    check: 'Audit:',
    checkTitle: 'Audit',
    opinion: 'Audit comments:',
    opinionTable: 'Audit comments',
    suggest: 'Review suggestions:',
    businessTip: 'The original exhibitor applied to reduce the booth or withdraw from the exhibition. The trading group must arrange a new exhibitor for the vacant booth. ',
    applyTip: 'Check and filter the number and location of booths with red and black lists',
    oldEnterpriseName: 'Original business name:',
    returnNum: 'Return booth number:',
    boothNum: 'Number of booths:',
    boothNumTable: 'number of booths',
    verify: 'check',
    backNum: 'Returned booth number:',
    index: 'serial number',
    depart: 'department',
    partName: 'node name',
    setNewEnterprise: 'Set new business:',
    businessDelegation: 'transaction group:',
    businessDelegationTable: 'transaction group',
    detection: 'detection',
    business: 'Business:',
    swapNum: 'Exchange booth number:',
    reviewMsg: 'Return, the current audit information will be lost, is it OK to return? ',
    addenterprise: 'Add a business',
    transactionReview: 'transaction group review',
    adjuestType: 'Adjust type',
    schemeStatus: 'record status',
    businessSelect: 'The selected business that needs to arrange location',
    baseInfo: 'Enter basic information',
    arrangeNum: 'Arrange the number of booths',
    arrangeCode: 'Arrange the booth number',
    reviewTime: 'Approval time',
    reviewPerson: 'Approver',
    reviewDescription: 'Audit Description',
    businessArrange: 'Business association location arrangement',
    operator: 'operator',
    seatReviewLable: 'Booth position arrangement plan review',
    seatApplyLable: 'Booth position arrangement proposal',
    patchReviewTitle: 'Booth position adjustment plan review',
    patchAddTitle: 'The booth position adjustment program is added',
    seatAdjustReview: 'Location Adjustment Review',
    seatTips: 'Poverty-stricken enterprises submit directly to the Foreign Trade Center for review',
    uploadTips: 'Only upload jpg/png files',
    adjustReviewTitle: 'Booth position adjustment plan adjustment review',
    adjustAddTitle: 'Booth position arrangement adjustment',
    exhibitionTypeTips: 'Please select the type of deployment',
    seatPublicityTitle: 'Public Position Arrangement Plan Announcement',
    patchReleaseTitle: 'Patch scheme public announcement',
    applyCheckFirst: "Apply a bound scheme, you can't generate a scheme again",
    applyCheckSecond: 'The name of the exhibition area is inconsistent, please re-select',
    applyCheckThird: 'The nature of the booth is inconsistent, please re-select',
    applyCheckLast: 'The layout type is inconsistent, please re-select',
    arrangeNumTips: 'Please choose to arrange the number of booths',
    arrangeCodeTips: 'Please choose to arrange the booth number',
    adjustmentApplyTitle: 'Booth adjustment view',
    adjustmentReviewTitle: 'Booth adjustment review',
    selectBusinessTips: 'Please select corporate information',
    changeNumTips: 'Please enter the exchange booth number',
    setNew: 'Set new',
    setLabel: 'Settings',
    refuseResonTips: 'Please enter the reason for rejection',
    refuseFuncTips: "Apply a bound scheme, can't refuse'",
    reviewRecordTitle: 'audit result record',
    adjustApplyTitle: 'Modify adjustment request',
    adjustApplyAddTitle: 'Add adjustment request',
    adjustNumTips: 'Please select the adjustment quantity',
    boothCodeTips: 'Please select the booth number',
    adjustReasonTips: 'Please fill in the reason for adjustment',
    adjuestContentTips: 'Please select the adjustment content',
    checkTips: 'Please tick',
    imageTips: 'Upload attachments can only be in jpg/png format!',
    imageSizeTips: 'Upload attachments cannot exceed 10M!',
    programDeleteTips: 'Do you want to delete the application?',
    programCancelTips: 'Is the application cancelled?',
    patchCancelTips: 'Exceeding the right operation, is the applicant voluntarily withdrawing? ',
    refuseSuccess: 'Reject success',
    batchSubmit: 'bulk submission',
    submitSuggest: 'Submit comments',
    submitSuggestTips: 'Please fill in the comments',
    checkBoothCode: 'Please tick the booth number',
    boothCodeTable: 'Booth number',
    onlineApplyTips: 'Return, the current page information will be lost, is it OK to return? ',
    associationLabel: 'Business Association Name',
    association: 'business Association',
    reviewResult: 'audit result',
    beforeBoothCode: 'Adjust the front booth number',
    batchRefuse: 'bulk reject',
    batchRefuseMsg: 'Reject opinion',
    batchRefuseTips: 'Please enter a rejection opinion',
    adjust: 'Adjustment',
    seatAdjust: 'Booth adjustment',
    boothNoExistInfo: 'The corresponding booth does not exist, please adjust and then import',
    specialTitle: 'Select area information',
    adjustMentTips: 'The selected booth number is inconsistent with the number of booths and cannot be exchanged',
    associationFormLabel: 'Business Association:',
    dialogInfo: "There is no exhibition hall information under the exhibition area, can't submit application",
    enterpriseArrangeInfo: 'Please select at least one company to adjust booth number information',
    gotoDetailInfo: 'Switch the details page the current page data will be lost, please save or submit and then switch',
    landInfo: 'The number of recommendations for the company should be consistent with the island type of booths',
    lessInfo: "Please fill in the reason for 'the number of booths is less than the recommended number'",
    selectOneTips: 'Only one type of booth can be selected for operation',
    adjustInfo: 'Please apply for the booth adjustment before you can save or submit',
    exportPageMsg: 'Please save before exporting the plugin image! ',
    isNewThemeArea: 'Whether the new theme area:',
    isNewThemeAreaTips: 'Please choose whether to create a new theme area',
    isNewThemeAreaTimeTips: 'Now is not a new theme exhibition area to arrange time, can not apply for a program',
    isUnifyArrange: 'Whether it is a unified exhibition area:',
    isUnifyArrangeTips: 'Please choose whether it is a unified exhibition area',
    isUnifyArrangeTimeTips: 'Now is not a unified exhibition area to arrange time, can not apply for a program',
    centralTimeTips: "Now is not the time allocated for the Central Channel Pavilion, you can't apply for a plan",
    autoArrangTimeTips: 'Now is the brand booth time, the automatic arrangement can not be arranged'
  },
  // 海关税则号
  SeaTariffNumberLang: {
    query: 'Query',
    reset: 'reset',
    seaTariffInquiry: 'Customs Tariff Number Inquiry',
    seaTariff: 'Customs Tariff Number',
    year: 'year',
    commodityCode: 'commodity code',
    productName: 'product name',
    extension: 'Recommended extension',
    exhibitionArea: 'Suggested exhibition area',
    category: 'Adjust category',
    instructions: 'Adjustment instructions',
    reason: 'adjust the reason',
    download: 'Download excel',
    export: 'export',
    suggestion: 'Adjustment suggestion',
    directory: 'directory query',
    catalogInquiry: 'Product Catalog Query',
    exclude: 'Remove directory query',
    elimination: 'removal instructions',
    catalogClassification: 'catalog classification',
    type: 'application type',
    changeType: 'change type',
    handling: 'Handling advice',
    changeDescription: 'change source description',
    changeSource: 'Change source product code',
    originalCode: 'Original product code',
    originalName: 'Original product name',
    status: 'status',
    reject: 'Reject',
    pass: 'pass',
    newExhibitionArea: 'Additional Pavilion',
    import: 'import',
    view: 'View',
    edit: 'Modify',
    add: 'add',
    delete: 'delete',
    submit: 'submit',
    setDeadline: 'set deadline time',
    format: 'Select download format',
    document: 'Select import document',
    confirm: 'OK',
    cancel: 'Cancel',
    return: 'return',
    suggestedFeedback: 'recommended feedback',
    feedback: 'Feedback',
    operation: 'operation',
    applyBtn: 'Apply',
    suggestedReview: 'Recommended review',
    review: 'Audit',
    auditor: 'auditor',
    post: 'post',
    explain: 'Description',
    explainRequired: 'Review rejection, description required',
    application: 'Adjust application',
    enterprise: 'Application unit',
    tradingGroup: 'transaction group',
    association: 'Business Association',
    applicationReview: 'Request for review',
    initiator: 'initiating unit',
    opinion: 'Audit opinion',
    startTime: 'Starting time',
    endTime: 'End Time',
    department: 'department',
    departmentReview: 'Department review',
    results: 'approval results',
    down: 'Download',
    foreign: 'Foreign Trade Division Review',
    total: 'total',
    newCodeNumber: 'new code number',
    editCodeNumber: 'Modify the number of codes',
    deleteCodeNumber: 'delete code number',
    selectPlaceholder: 'Please select',
    inputPlaceholder: 'Please enter',
    max200: 'Enter up to 200 characters',
    max255: 'Enter up to 255 characters',
    delData: 'Are you sure you want to delete the selected data? ',
    changedToDelete: 'The current product code has no exhibition area. If it is deleted, adjust the category to delete',
    tips: 'prompt',
    successful: 'Operation succeeded',
    undelete: 'Canceled delete',
    changedToCull: 'The current product code is the last exhibition area. If it is deleted, the directory classification is changed to cull',
    notMoreThan8: 'consisting of numbers and no more than 8 digits',
    noSpaces: 'There must be no spaces at the beginning and end',
    selectYearFirst: 'Please select the year first',
    importSuccessfully: 'File import success! ',
    importFailed: 'File import failed, please re-import! ',
    submissionFailed: 'Submit failed',
    empty: 'Data cannot be empty',
    notBeenFullySubmitted: 'The data has not been fully submitted successfully',
    error401: '401 error, please contact the administrator',
    error404: 'Download failed, please contact the administrator',
    errorServe: 'Server error, please contact the administrator',
    noNewExhibitionArea: 'No new exhibition area',
    feedbackView: 'Suggest feedback',
    applicationView: 'Adjust application view',
    isRequired: 'When the catalog is classified as an item, the recommended area is required',
    isSubmit: 'Are you sure you want to submit data?',
    cancelledSubmission: 'Cancelled submission',
    excludes: 'cull',
    commodity: 'goods',
    noChange: 'no change',
    editProductName: 'Modify the product name',
    isNewExhibitionArea: 'When adding a new exhibition area, the adjustment instructions are required',
    catalogManagement: 'Product Catalog Management',
    excludingDirectoryManagement: 'Remove directory management',
    noData: 'The list has no data, can not be added',
    noRequired: 'There is a data submission record for the incomplete process, no more can be added',
    noImport: 'Data submission record with unfinished process, can not be imported again',
    isDeadline: 'Application deadline is',
    hasExpired: 'The application time has expired and you can no longer apply',
    unsubmitted: 'unsubmitted',
    pendingReview: 'Pending review',
    auditNotPassed: 'Audit not passed',
    departmentApproval: 'Department approval',
    foreignApproved: 'Foreign Trade Division approved',
    foreignFailed: 'Foreign Trade Division failed to pass the review',
    statistics: 'Catalog change statistics',
    notSubmit: 'No data to submit',
    submitWait: 'The submit operation was successful, please wait for background processing',
    wait: 'wait'
  },

  CommonPayLang: {
    refuseReason: 'Reject the reason',
    paymentExamine: 'payment form review',
    collection: 'cash collector',
    paymentNo: 'payment form number',
    examineState: 'audit status',
    paymentDate: 'payment date',
    to: 'to',
    group: 'group',
    collectionAdmin: 'Receiving Administrator',
    advancePayment: 'advance payment',
    cash: 'cash',
    check: 'check',
    alipay: 'Alipay',
    wechat: 'WeChat',
    bankcard: 'bank card',
    refundAmount: 'Refund amount',
    collectAmount: 'contribution amount',
    collectTime: 'payment time',
    remark: 'remarks',
    refuse: 'refuse',
    examined: 'reviewed',
    unExamine: 'Unreviewed',
    refused: 'Rejected',
    passRecord: 'Are you sure you want to review the record?',
    examineSuccess: 'Audit success',
    sureBatch: 'You are sure to batch',
    yeah: '',
    batch: 'batch',
    selectone: 'Please select at least one record',
    refuseRecord: 'Are you sure you want to reject this record?',
    refuseSuccess: 'Dismissed success',
    success: 'success',
    fail: 'fail',
    examine: 'audit',
    groupName: 'group name',
    groupManage: 'Group management',
    invalidChar: 'Cannot contain special characters or spaces',
    max30: 'Cannot exceed 30 characters',
    max100: 'Cannot exceed 100 characters',
    groupNameRequired: 'Please enter a group name',
    saveSuccess: 'Data saved successfully',
    deleteConfirm: 'Data cannot be recovered after deletion, are you sure to delete',
    invoiceView: 'View electronic invoice',
    orderNo: 'order number',
    invoiceNo: 'invoice number',
    invoiceDate: 'invoice date',
    invoiceAmount: 'invoice amount',
    buyerNo: 'purchasing tax number',
    buyerCompany: 'Purchasing company name',
    buyerCompanyPhone: 'Purchasing company phone',
    buyerBankNo: 'Purchasing Bank Account Number',
    customNo: 'customer phone',
    email: 'email',
    invoiceSendType: 'Invoice Sending Method',
    invoiceCompany: 'Invoicing company name',
    eleInvoiceAddr: 'electronic invoice address',
    orderType: 'order type',
    invoiceType: 'invoice type',
    orderNum: 'order quantity',
    taxRate: 'tax rate',
    tax: 'tax',
    invoiceManage: 'electronic invoice query',
    max50: 'Cannot exceed 50 characters',
    addressExpire: 'The invoice address has expired or does not exist',
    linkInvalid: 'Unable to get invoice link',
    accountType: 'account type',
    invoiceReceiveMethod: 'Invoice Receiving Method',
    creditLetterCode: 'Letter of Credit Code',
    invoiceTitle: 'invoice header',
    taxNumber: 'tax number',
    channelNumber: 'Channel number',
    bankName: 'Bank name',
    bankAccountNum: 'Bank account number',
    companyName: 'company name',
    companyTel: 'company phone',
    companyAddr: 'company address',
    accountEmail: 'mailbox',
    mobilePhoneNum: 'mobile number',
    accountProtocol: 'Prepaid Account Opening Agreement',
    protocolRemark: " Dear User: Hello! You will sign the <<Mobile Payment Service Customer Service Agreement>> (hereinafter referred to as 'this Agreement') with the Company, and your related rights and obligations will be stipulated in this Agreement. At the same time, you are reminded of the agreement on the exemption clause in Article 6 of this Agreement.",
    confirmProtocol: 'I have read the above agreement and agree',
    illegal: 'not legal',
    unDraft: 'You still have unfinished draft information, please continue',
    cancelConfirm: 'The current page data will not be saved after cancellation. Are you sure you want to cancel?',
    readProtocol: 'Please read the prepaid account opening agreement and check the read!',
    activeConfirm: 'Cannot be modified after the account is activated. Are you sure you want to activate the account?',
    activeSuccess: 'Congratulations, the account has been activated successfully!',
    activeFail: 'Sorry, account activation failed!',
    saveFail: 'Save failed!',
    rechargeAccountView: 'View prepayment account',
    rechargeAccountNum: 'Prepayment account',
    accountBalance: 'account balance',
    activeDate: 'activation date',
    activeState: 'active state',
    rechargeAccountManage: 'Prepaid Account Management',
    invoiceCheckIn: 'VAT invoice registration',
    addedTaxinvoiceNo: 'VAT invoice number',
    elecInvoiceNo: 'Original electronic invoice number',
    sureToCheckIn: 'Are you sure you want to register?',
    checkInSuccess: 'Registration succeeded!',
    invoiceTime: 'invoice date',
    invoiceMan: 'registered person',
    refundTransferDate: 'Refund arrival date (days)',
    refundLimit: 'On-site refund approval limit (yuan)',
    plusRequired: 'Please enter a value greater than 0',
    sureToConfig: 'Are you sure you want to configure?',
    configSuccess: 'Configuration succeeded',
    newPayment: 'Add a new payment slip',
    newDailyPayment: 'Add a daily statement',
    handinAmount: 'receipt amount',
    pendHandinAmount: 'Amount to be paid',
    sureToAddPayment: 'Are you sure you want to add this payment slip?',
    dailyBalanceAmount: 'Total balance of daily balance',
    sureToAddDaily: 'Are you sure you want to add this day statement?',

    pleaseInput: 'Please enter',
    invalid: 'Not legal',
    enable: 'Enable',
    disable: 'deactivate',
    back: 'return',
    operationFail: 'Operation failed',
    dataSaveSuccess: 'Data saved successfully',
    deleteWarning: 'The data cannot be recovered after deletion. Are you sure to delete? ',
    startDate: 'start date',
    endDate: 'end date',
    bankAccountManage: 'Bank Account Management',
    bankAccount: 'bank account number',
    state: 'state',
    bankCard: 'card number',
    bankCode: 'issuing bank',
    collectAccountManage: 'receipt account management',
    collectionAccount: 'receipt account number',
    chargeType: 'Charge type',
    exhibitType: 'Exhibition General',
    exhibitName: 'Exhibition name',
    nativeName: 'exhibition abbreviation',
    exhibitNo: 'Exhibition number',
    organizeUnit: 'Organizer',
    prepayCollect: 'Prepaid payment',
    normalCollect: 'Ordinary collection',
    no: '第',
    session: 'session',
    collectRecords: 'Receipt record management',
    viewCollectDetails: 'View payment details',
    bankBillNo: 'Bank Order Number',
    payMethod: 'payment method',
    collectMethod: 'Receipt method',
    payBankName: 'payment branch',
    payBankAccount: 'payment account',
    payCompanyName: 'payment company',
    payState: 'payment status',
    collectionAmount: 'Number of receipts',
    collectionDate: 'receipt date',
    collectionFlowNo: 'receipt slip number',
    collectBankName: 'receipt branch',
    collectBankAccount: 'Receipt Account',
    currency: 'currency',
    onlineCollect: 'Online collection',
    offlineCollect: 'On-site collection',
    awaitPay: 'Pending payment',
    failPay: 'Payment failed',
    hasPay: 'paid',
    collectorsManage: 'Casher Management',
    collector: 'receiver',
    collectorAccount: 'account',
    name: 'name',
    username: 'username',
    mobilephone: 'phone number',
    groupCategory: 'group',
    upperAdmin: 'owner',
    collectProject: 'Receipt item',
    sex: 'gender',
    idCard: 'ID number',
    Import: 'import',
    male: 'male',
    female: 'female',
    fileSizeNotExceed10MB: 'The file size cannot exceed 10MB',
    excelFileOnly: 'Only upload Excel file',
    importSuccess: 'Imported successfully',
    importFail: 'Import failed',
    confirmBatchDelete: 'Are you sure you want to delete it in bulk? ',
    confirmBatchEnable: 'Are you sure you want to enable it in bulk? ',
    confirmBatchDisable: 'Are you sure you want to disable it in bulk? ',
    batchDeleteSuccess: 'Bulk delete success',
    batchEnableSuccess: 'Batch enable success',
    batchDisableSuccess: 'Bulk disable success',
    batchDeleteFail: 'Bulk delete failed',
    batchEnableFail: 'Batch enable failed',
    batchDisableFail: 'Batch disable failed',
    atLeastSelectOne: 'Select at least one record',
    otherPay: 'Alipay and WeChat payment',
    thidPay: 'Third party payment',
    wechatPay: 'WeChat payment',
    aliPay: 'Alipay payment',
    waitToPay: 'Please wait patiently for payment to complete',
    warmTips: 'warm tips',
    unionPay: 'Personal and corporate payments',
    orderAmount: 'order amount',
    merchantName: 'Business name',
    yuan: 'yuan',
    personalUnion: 'Personal online banking',
    firmUnion: 'Corporate online banking',
    goToPay: 'Pay to online banking',
    paySuccess: 'Payment completed',
    payCancel: 'Payment canceled',
    confirmPay: 'Are you sure you want to pay? ',
    noSupport: 'Not supported yet',
    cancelPay: 'Are you sure you want to cancel the payment? ',
    prepayRefundRecords: 'prepayment refund record',
    applyDate: 'application date',
    receiveBankName: 'Import branch',
    receiveBankAccount: 'Import account',
    approving: 'Approval',
    approved: 'Approved',
    rejected: 'Rejected',
    passed: 'passed',
    billNo: 'document number',
    prepayAccount: 'prepayment account',
    Renminbi: 'RMB',
    prepayChargeRecords: 'prepaid recharge record',
    chargeMethod: 'Recharge method',
    chargeDate: 'Recharge date',
    chargeAmount: 'charge amount',
    bankReceipt: 'Bank ticket',
    orderDate: 'order date',
    payDate: 'payment date',
    fee: 'handling fee',
    orderState: 'order status',
    bankAccountType: 'Account Type',
    bankNote: 'Bank Identification',
    payComment: 'Payment note',
    refundableableAmount: 'returnable amount',
    confirmCharge: 'Are you sure you want to top up? ',
    onlinePay: 'Online payment',
    offlinePay: 'Offline payment',
    orderSuccess: 'success',
    orderFail: 'failed',
    personalAccount: 'personal account',
    firmAccount: 'corporate account',
    prepayCharge: 'prepaid recharge',
    jumpToPaymentPage: 'Going to the payment page',
    prepayAccountType: 'account type',
    charge: 'charge',
    inputValidAmount: 'Please enter the correct amount',
    getPrepayAccountFail: 'Get prepaid account failed',
    confirmPrepayCharge: 'Are you sure you want to top up? ',
    invoiceReceivedMethod: 'Invoice receiving method',
    openBankName: 'Bank name',
    openAccount: 'Bank account number',
    companyAdd: 'unit address',
    activateDate: 'activation date',
    activateState: 'active state',
    export: 'export',
    activated: 'activated',
    inactivated: 'not activated',
    approvalComment: 'Approval opinion',
    max200: 'Cant exceed 200 characters',
    approvalOperation: 'Approval operation',
    invoiceMaked: 'Opened',
    invoiceUnmaked: 'not open',
    onlineRefund: 'Online refund',
    offlineRefund: 'On-site refund',
    cashRefund: 'cash',
    onlineBanking: 'Internet Banking',
    confirmSubmit: 'Are you sure you want to submit? ',
    approvalSubmitSuccess: 'Approval submission success',
    confirmCancelApproval: 'Are you sure you want to cancel the refund review? ',
    refundApproval: 'Refund review',
    invoiceState: 'invoice status',
    refundDate: 'Refund date',
    refundMethod: 'Refund method',
    refundType: 'Refund type',
    approvalPass: 'pass',
    approvalUnpass: 'Do not pass',
    approvalReject: 'Reject',
    approvalSubmit: 'submit',
    viewApprovalLog: 'Click to view the approval log',
    prepayRefundApply: 'Prepaid refund request',
    exceedBalance: 'The amount you entered cannot exceed your balance',
    confirmRefund: 'Are you sure you want to request a refund? ',
    refundSuccess: 'The request for refund is successful. It is expected to arrive within 15 working days. Please be patient! ',
    confirmCancelRefund: 'Are you sure you want to cancel your refund request? ',
    confirmResubmit: 'Are you sure you want to resubmit your refund request? ',
    submitSuccess: 'Submit successfully',
    rejectComment: 'Reject the opinion',
    resubmit: 'resubmit',
    batchPass: 'Batch through',
    batchReject: 'bulk reject',
    refundDetail: 'Refund details',
    refundOrderNo: 'Refund Order Number',
    refundFlowNo: 'Refund serial number',
    refundRecords: 'Refund Order Records',
    awaitRefund: 'Pending refund',
    refundFail: 'Refund failed',
    refunded: 'Refunded',
    refundState: 'Refund status',
    merchantId: 'Business number',

    paymentMethod: 'payment method',
    paymentMethodName: 'name',
    paymentMethodCode: 'code',
    selectState: 'Please select state',
    paymentMethodManage: 'Payment Method Management',
    fillPaymentMethodName: 'Please fill in the payment method name',
    fillPaymentMethodCode: 'Please fill in the payment method code',
    opratorFail: 'Sorry, the operation failed',
    enterpriseOperator: 'Corporate Operator',
    enterpriseOperatorName: 'operator name',
    enterpriseOperatorRechargeAccount: 'prepayment account',
    selectRechargeAccount: 'Please select a prepayment account',
    payPassword: 'Payment Password',
    enterpriseOperatorManage: 'Enterprise Operator Management',
    fillEnterpriseOperatorName: 'Please enter the operator name',

    fillMobilePhoneNum: 'Please enter the phone number',
    fillIdCard: 'Please enter the ID number',
    fillPayPassword: 'Please enter the payment password',
    idCardError: 'The ID number is in the wrong format',
    mobilPhoneError: 'The phone number is in the wrong format',
    refundRegisterRecords: 'On-site refund registration record',
    refundRegisterBillNo: 'Order number',
    purchaserName: 'receiver name',
    registerDate: 'registration date',
    purchaserBankAccount: 'Payee Bank Card Number',
    purchaserBankName: 'Receiver bank account',
    purchaserTel: "Receiver's contact number",
    remitApproveRecords: 'Auditing offline remittance records',
    approveRemark: 'Audit comments',
    remitApproveRecordsManage: 'Offline remittance record management',
    remitAmount: 'remittance amount',
    payBankAccountNum: 'export account',
    payBankAccountName: 'Export Account Bank',
    remitAttachment: 'attachment',
    remitNotes: 'Remittance Postscript',
    fillApproveRemark: 'Please enter a review comment',
    remitRegisterRecords: 'Offline remittance registration list',
    remitDate: 'Remittance date',
    clickUpload: 'Click to upload',
    cancelTips: 'The form data is not saved after canceling, is it canceled?',
    submitTips: 'Cannot be modified after submission, do you submit the form?',
    fileSizeNotExceed1MB: 'The file size cannot exceed 1MB',
    imageFileOnly: 'Only upload image files of type png, jpg, jpeg',
    fileNameLenghMax50: 'The file name cannot exceed 50',
    fileNumOnlyOne: 'The current limit selects 1 file',
    getCollectAccountFail: 'Acquisition of the current category of the collection account information failed, please select another category or contact the administrator',
    selectRemitAttachment: 'Please select the remittance voucher first',
    inputCorrectAmt: 'Please enter the correct amount',
    selectDate: 'Select date',
    inputRemitAmount: 'Please enter the remittance amount',
    inputPayBankAccountName: 'Please enter the name of the export account',
    inputPayBankAccountNum: 'Please enter the export account',
    payBankAccountNumError: 'The export account is not legal',
    selectRemitDate: 'Please select the remittance date',
    inputCompanyName: 'Please enter the company name',
    inputCurrency: 'Please select the coin type',
    billConfig: 'Reconciliation Configuration',
    billConfigManage: 'Reconciliation Configuration Management',
    billConfigBankName: 'Reconciliation Bank',
    inputBillConfigBankName: 'Please enter the reconciliation bank name',
    billConfigBankCode: 'Bank Code',
    inputBillConfigBankCode: 'Please select bank code',
    max4: 'The length cannot exceed 4 characters',
    Max10: "Can't exceed 10 characters",
    Max1: "Can't exceed 1 character",
    Max2: "Can't exceed 2 characters",
    Max20: "Can't exceed 20 characters",
    nativeFtpUrl: 'local ftp path',
    inputNativeFtpUrl: 'Please enter the local ftp path',
    getFileMethod: 'File acquisition method',
    inputGetFileMethod: 'Please enter the file acquisition method',
    oSOfFtp: 'ftp operating system',
    inputOSOfFtp: 'Please enter the operating system where ftp is located',
    ftpIpAddress: 'ftp ip address',
    inputFtpIpAddress: 'Please enter ftp ip address',
    ftpDir: 'ftp directory',
    inputFtpDir: 'Please enter the ftp directory',
    ftpPort: 'ftp port',
    inputFtpPort: 'Please enter ftp port',
    ftpUserName: 'ftp username',
    inputFtpUserName: 'Please enter ftp username',
    ftpPassword: 'ftp password',
    inputFtpPassword: 'Please enter the ftp password',
    billConfigFileName: 'file name',
    inpuptBillConfigFileName: 'Please enter a file name',
    readStartLine: 'Read start line',
    inputReadStartLine: 'Please enter the file from the first few lines',
    splitChar: 'delimiter',
    inputSplitChar: 'Please enter a separator',
    isEscape: 'Do you need to escape?',
    selectIsEscape: 'Please choose whether you need to escape',
    amountUnit: 'amount of units',
    selectAmountUnit: 'Please select the amount unit',
    billConfigDate: 'Reconciliation Date',
    selectBillConfigDate: 'Please select the reconciliation date',
    dateAddday: 'offset time',
    inputDateAddday: 'Please enter the offset time',
    swiftTime: 'Pow the time',
    inputSwiftTime: 'Please enter the billing time',
    timeSchedule: 'scheduling time',
    inputTimeSchedule: 'Please enter the scheduling time',
    addDayOnlyNum: 'The offset time must be a numeric value',
    readStartLineOnlyNum: 'Read start line must be a numeric value',
    all: 'all',
    rechargeAccountExist: 'This account type has a prepaid account',
    pleaseSelect: 'Please Select',

    capitalAmount: 'Capital Amount',
    boothFeeRegistration: 'Booth fee registration',
    configFeeRegistration: 'configuration fee registration',
    boothFeeRegList: 'Booth fee registration list',
    configFeeRegList: 'configuration fee registration list',
    boothFee: 'Booth fee',
    configurationFee: 'configuration fee',
    transUnitType: 'transaction type',
    unitName: 'unit name',
    exportBank: 'Export bank',
    exportAccount: 'export account',
    importBank: 'Import Bank',
    importAccount: 'Import account number',
    pleaseEnterNum: 'Please enter a number between 0~999999999',
    maxTwoDecimalPlaces: 'Enter up to two decimals',
    onlyPositiveNum: 'Can only enter a positive integer',
    provincialTradingGrp: 'Provincial Trade Group',
    centralTradingGrp: 'Central Enterprise Trading Group',
    businessUnit: 'Business Unit',
    confirmRegist: 'Are you sure you want to register? ',
    confirmCancelBooth: 'The current page data will not be saved after cancellation. Are you sure you want to cancel? ',
    projectType: 'project type',
    registerPerson: 'registered person',
    orderPaying: 'The order is being paid',
    orderHasPaid: 'Order has been paid successfully',
    orderPaidFail: 'Order payment failed',

    addCountConfirm: 'The account does not exist. Continue to add the account',

    dailySummary: 'Daily summary',
    dateOfPayment: 'Date of payment',
    dailyStatementNumber: 'Daily statement number',
    theAmountReceivedOnTheDay: 'The amount received on the day',
    sameDayPaymentAmount: 'Same day payment amount',
    cumulativeCollectionAmount: 'Cumulative collection amount',
    cumulativeAmountPaid: 'Cumulative amount paid',
    amountToBePaid: 'Amount to be paid',
    print: 'print',

    reconcileResultRecords: 'Online reconciliation results',
    bankOrderNo: 'transaction order number',
    transType: 'transaction type',
    transState: 'transaction status',
    transDate: 'transaction date',
    payment: 'payment',
    refund: 'Refund',
    balanced: 'Accounting',
    unbalanced: 'The account is not flat',
    prepayOrder: 'prepayment order',
    normalOrder: 'Ordinary order',
    isPrepay: 'Order Type',
    isBalanced: 'Balanced',
    diffComment: 'Differential description',
    diffAmount: 'Difference Amount',
    bankTransState: 'Bank Transaction Status',
    localTransState: 'System transaction status',
    bankTransAmount: 'Bank transaction amount',
    localTransAmount: 'System transaction amount',

    cashierDailySummary: 'cashier daily summary',
    collectionTime: 'collection time',
    posQuickPayment: 'POS quick payment',
    subtotal: 'subtotal'
  },
  // 会议论坛
  MettingForumLang: {
    sponsorManagement: 'Conference Sponsorship Management',
    guestInfoManagement: 'Guest Information Management',
    audienceInfoManagement: 'Audience Information Management',
    labelManagement: 'tag management',
    categoryManagement: 'category management',
    industryManagement: 'Conference sponsorship management',
    exhibitionManagement: 'Exhibition Management',
    unitManagement: 'Home unit management',
    add: 'Add',
    delete: 'delete',
    operation: 'operation',
    update: 'Modify',
    import: 'import',
    reset: 'Reset',
    query: 'Query',
    disable: 'disabled',
    enable: 'Enable',
    index: 'index',
    prvPage: 'previous page',
    nextPage: 'Next page',
    close: 'close',
    cancel: 'cancel',

    sponsorLevel: 'Sponsorship level',
    sponsorForumCost: 'Sponsorship fee',
    sponsorProfit: 'Sponsorship',
    guestName: 'guest name',
    name: 'name',
    orgName: 'Affiliate',
    position: 'position',
    mobile: 'phone',
    email: 'mailbox',
    repeatInfoTips: 'Repeat message hints',
    repeatInfoCompare: 'Repeat information comparison',
    replaceOrgData: 'Replace the original data',
    keepOrgData: 'Keep original data',
    originalData: 'original data',
    newData: 'new data',
    notNull: "Can't be empty",
    inputMobileTips: 'Please enter the correct mobile number',
    inputSpecialTips: 'Input cannot contain special characters',
    pleaseEnterContent: 'Please enter the content',
    pleaseSelect: 'Please select',
    isNull: ' is empty',
    isNotNull: "Can't be empty",
    yes: 'Yes',
    no: 'No',

    assistantName: 'helper name',
    guestAssistant: 'Guest Assistant',
    assistantPosition: 'Assistant position',
    assistantMobile: 'helper phone',
    assistantEmail: 'Assistant Mailbox',
    companyName: 'company name',
    industry: 'Industry',
    industryUnit: 'Industry',
    exhibition: 'Exhibition area',
    isImportantClient: 'Important customer',
    confirm: 'confirm',
    browse: 'Browse',
    attachment: 'attachment',
    downloadTemplate: 'Download template',
    labelName: 'tag name',
    sort: 'sort',
    status: 'status',
    categoryName: 'category name',
    industryName: 'Industry name',
    exhibitionName: 'Exhibition name',
    isEnable: 'whether enabled',
    unit: 'Home unit'
  },

  //进口展招商 证件业务
  badgeBusinessLang: {
    personalUserBadgeApplication: 'Personal User ID Application',
    name: 'name:',
    idCardNo: 'ID number:',
    period: 'number of periods:',
    gearPosition: 'Gear:',
    dayNumber: 'days:',
    startDate: 'start date:',
    idCardScanFront: 'Identity Scanner Front:',
    licenseLocation: 'License Location:',
    idCardScanReverse: 'The reverse side of the ID card scan:',
    change: 'change',
    avatar: 'avatar:',
    cancel: 'cancel',
    submit: 'submit',
    pleaseEnter: 'Please enter',
    pleaseChoose: 'Please select',
    levelNameTips: 'The current number of companies has no indicators',
    selectDate: 'Select date',
    uploadPrompt: 'The uploaded image size cannot exceed 500K!',
    uploadImgTips: 'Upload avatar image can only be JPG/PNG/JEPG format',
    uploadSuccess: 'Upload succeeded',
    prompt: 'prompt',
    confirm: 'OK',
    viewAuditStatus: 'View Audit Status',
    nameTable: 'name',
    applicationTime: 'application time',
    numberOfPeriods: 'number of periods',
    numberOfDays: 'days',
    startingTime: 'starting time',
    feeLevel: 'gear',
    cost: 'cost',
    auditStatus: 'Audit Status',
    operation: 'operation',
    repeal: 'undo',
    viewReceipt: 'View receipt',
    repealReminder: 'Remove the reminder',
    repealPrompt: 'Are you sure to revoke?',
    departmentMessage: 'Your application for the application has not been reviewed, is it determined to revoke?',
    centerMessage: 'Your application for the application has been approved, but has not yet been certified, is it determined to be revoked?',
    repealSuccess: 'Undo successfully',
    badgeApplicationReview: 'Document application review',
    ownedEnterprise: 'owned company',
    badgeApplicationStatus: 'document application status',
    query: 'query',
    reset: 'reset',
    applicant: 'applicant',
    systemPromptMessage: 'System prompt information',
    view: 'View',
    modify: 'modify',
    adminViewPersonalInfo: 'Administrator View Personal Information',
    failureReason: 'No reason',
    theReason: 'Cause:',
    attributiveEnterprise: 'Home business:',
    idCardScan: 'Identity Scanner:',
    auditPassed: 'Audit passed',
    auditNotPassed: 'Audit failed',
    entAdminSubmitApplication: 'Enterprise administrator submits application',
    identityNumber: 'ID number',
    badgeApplication: 'Application for a permit',
    badgeTipOneF: 'Prompt 1: The business',
    indexTipOneA: 'Hint: Your business',
    indexTipOneB: 'Total',
    indexTipOneC: 'indicator',
    indexTipOneD: 'one, remaining',
    indexTipOneE: 'A.',
    contactNumber: 'contact phone',
    mailbox: 'mailbox',
    edit: 'edit',
    takeBadgeAddress: 'License Location',
    addPersonalUser: 'Add individual user',
    submitApplication: 'Submit application',
    alreadyAppliedCertification: 'Apply for certification',
    submitter: 'Submit',
    pleaseSelectData: 'Please select data',
    submitApplicationTip: 'There are insufficient indicators, please re-select',
    submitSuccess: 'Submit application successfully',
    agencyAdminSubmitApplication: 'Institutional Administrator Submits Application',
    enterpriseNameTable: 'company name',
    unifiedSocialCreditCode: 'Unified Social Credit Code',
    contactInformation: 'Contact',
    conferenceAdminSubmitApplication: 'The conference administrator submits the application',
    photoManagementTool: 'Photo Management Tool',
    setPicture: 'Setting the picture',
    rotate: 'rotate',
    screenshot: 'screenshot',
    receiptContent: 'Receipt content',
    idCard: 'Identity:',
    applyTime: 'application time:',
    fee: 'cost:',
    certificate: 'Voucher:',
    print: 'print',
    domesticTradeBuyers: 'Domestic trade buyers:',
    importBuyer: 'Imported Buyer:',
    all: 'All:',

    applicationDeadline: 'Document application time management',
    timeType: 'time type',
    domesticBuyers: 'Domestic Trade Buyers',
    importPurchaser: 'Imported Buyer',
    allType: 'all',
    validateBadgeDeadline: 'Please enter a positive integer within 0-24',
    validateFixedInteger: 'Please enter a positive integer within 9 digits',
    badgeCostRules: 'Certificate Fee Rules',
    costRule: 'cost rule',
    gearName: 'Gear name:',
    phaseOne: 'Phase 1:',
    phaseTwo: 'Phase II:',
    phaseThree: 'Phase III:',
    oneDay: 'One day:',
    twoDays: 'Two days:',
    threeDays: 'Three days:',
    fourDays: 'Four days:',
    wholePeriod: 'Full period:',
    earlyBirdDiscountRate: 'Early Bird Offer Rate:',
    qualificationContent: 'Qualification content:',
    amount: 'Amount:',
    newCostRule: 'Add cost rule',
    deleteRule: 'delete rule',
    firstPeriodBadgeAmount: 'One-time document amount:',
    secondPeriodBadgeAmount: 'Second period document amount:',
    thirdPeriodBadgeAmount: 'Three-phase certificate amount:',
    oneDayTable: 'One day',
    twoDaysTable: 'Two days',
    threeDaysTable: 'Three days',
    fourDaysTable: 'Four days',
    fiveDaysTable: 'Five days',
    wholePeriodTable: 'full period',
    earlyBirdDiscountRateTable: 'early bird discount rate',
    qualificationContentTable: 'Qualification Content',
    validateBadgeFee: 'Can only be a number and the integer does not exceed 5 digits, the decimal does not exceed 2 digits',
    selectGear: 'Please select a gear',
    enterAmount: 'Please enter the amount',
    enterDiscountRate: 'Please enter the discount rate',
    enterQualificationContent: 'Please enter the qualification content',
    badgeCostLength: 'The length cannot exceed 100 characters',
    add: 'add',
    deleteGearTipsA: 'Please select the gear first',
    deleteGearTipsB: 'You will delete the corresponding three-stage gear cost rule, be sure to delete?',
    deleteSuccess: 'delete successfully',
    setDefaultIndex: 'Set default metrics',
    dailyApplicationLimit: 'Daily application limit',
    eachPeriodLimit: 'free limit per period',
    enterpriseDefaultIndex: 'Enterprise default metric',
    modifyLimitTotal: 'Modify the maximum number of caps',
    limitNumber: 'Upper limit number:',
    ceiling: 'upper limit quantity',
    enterLimitNumber: 'Please enter the upper limit quantity',
    modifyDefaultIndex: 'Modify default metrics',
    indexName: 'indicator name:',
    buyerType: 'Purchaser Type:',
    specialInvitationA: 'Special invitation:',
    importantA: 'Important:',
    ordinaryA: 'Ordinary:',
    firstPeriodDefaultIndex: 'First-phase default indicator',
    secondPeriodDefaultIndex: 'Second phase default indicator',
    thirdPeriodDefaultIndex: 'Three-phase default indicator',
    specialInvitationB: 'Special invitation',
    importantB: 'Important',
    ordinaryB: 'Ordinary',
    enterIndexNumber: 'Please enter the number of indicators',
    eachEntCertificationIndex: 'Management of Enterprise Certification Indicators',
    number: 'quantity',
    enterpriseNo: 'company number',
    details: 'details',
    totalIndex: 'Total indicator',
    availableIndex: 'available indicator',
    adjustment: 'adjustment',
    viewIndex: 'View indicator details',
    adjustIndex: 'adjustment indicator',
    eachEntPresetIndex: 'Every enterprise preset indicator',
    presetIndexTotal: 'Total number of preset metrics:',
    agency: 'institution',
    extension: 'extension',
    preAdjustNumber: 'Pre-adjusted quantity',
    batchImport: 'bulk import',
    importSuccess: 'Imported successfully',

    enterpriseUserLabelInfo: 'Enterprise User Tag Information',
    customerType: 'customer type',
    phaseOneTable: 'Phase I',
    phaseTwoTable: 'Phase II',
    phaseThreeTable: 'Phase III',
    buyerTypeTable: 'Purchaser Type',
    sourceType: 'source type',
    invitationNumber: 'The number of invitations received in the session',
    activeTagsTable: 'active tag',
    chooseLabel: 'Please select a label',
    personalUserLabelInfo: 'Personal User Label Information',
    personalLabelSettings: 'Personal Label Settings',
    labelType: 'tag category:',
    labelName: 'tag name:',
    dataType: 'data type',
    activityListImport: 'Active list import',
    selectAtLeastOneLabel: 'Please select at least one label',
    customerTypeRuleSetting: 'Customer Type Rule Setting',
    rules: 'rules:',
    customerTypeA: 'Class A: A1 Domestic Trade Buyer A2 Import Buyer A3 All',
    customerTypeB: 'Class B: B1 Wholesale enterprise annual sales of 100 million yuan / retail enterprise 50 million B2 turnover exceeds 50 million B3 turnover exceeds 30 million',
    customerTypeC: 'Class C: C1 business scope meets the first product category C2 Business scope meets the first phase of the import exhibition product category C2 Business scope meets the second phase product category',
    rulesTable: 'rules',
    enterRule: 'Please enter a rule',
    iKnow: 'I know it',
    qualificationReview: 'Qualification Review',
    qualificationReviewPage: 'Qualification Review Page',
    enterContent: 'Please enter the content',
    enterpriseQualificationReview: 'Enterprise Qualification Review',
    enterpriseName: 'company name:',
    contactName: 'Contact Name:',
    idCardNoForm: 'ID card number:',
    unifiedSocialCreditCodeForm: 'Unified Social Credit Code:',
    idCardFont: 'ID card front:',
    idCardReverse: 'ID card reverse:',
    businessLicense: 'Business License:',
    qualificationPicture: 'Enterprise Supplement Qualification Picture:',
    businessLicenseValidityPeriod: 'Business license validity period:',
    buyerTypeForm: 'Purchasing type:',
    qualificationForm: 'Qualification:',
    classA: 'Class A:',
    classB: 'Class B:',
    classC: 'C class:',
    notPassingRecord: 'The current review does not pass the record (latest):',
    failureReasonForm: 'The reason why the audit failed:',
    reviewTimeForm: 'Audit time:',
    reviewerForm: 'Reviewer:',
    status: 'status',
    auditResult: 'audit result',
    reviewTime: 'review time',
    reviewer: 'reviewer',
    enterReason: 'Please enter the reason',
    firstGear: 'first gear',
    secondGear: 'second gear',
    thirdGear: 'third gear',
    fourthGear: 'fourth gear',
    fifthGear: 'Fiveth gear',
    applicationChannelControl: 'Apply Channel Control',
    enterpriseUniformCoding: 'Enterprise Uniform Coding',
    enterpriseCode: 'enterprise code',
    open: 'open',
    shutDown: 'closed',
    channelChangeTipsA: 'You will',
    channelChangeTipsB: 'The company applies for the channel, is it sure to continue',
    channelIsOpen: 'Channel is open',
    channelIsOff: 'Channel is closed',
    operationCanceled: 'Operation canceled',
    badgeTipsA: 'Hint 2: Date of admission for this application:',
    badgeTipsB: 'has received',
    badgeTipsC: 'applications',
    badgeTipsD: '.',
    validateearlyBirdDiscountRate: 'Not greater than 1 and up to 2 decimals',
    firstDay: 'First day',
    secondDay: 'The next day',
    thirdDay: 'The third day',
    fourthDay: 'Fourth day',
    fifthDay: 'The fifth day'
  },

  //归属关系管理
  ownershipManagementLang: {
    adminAuditEntOrg: 'Administrator reviewing corporate institutions',
    sessionNumber: 'the number of years',
    enterpriseName: 'company name',
    unifiedSocialCreditCode: 'Unified Social Credit Code',
    cooperationAgency: 'Cooperative agency',
    cooperationAgencyCode: 'Cooperative agency code',
    query: 'Query',
    reset: 'reset',
    pass: 'pass',
    enterpriseUserRequest: 'Enterprise User Request',
    initiatorEnterpriseName: 'Initiator (company name)',
    processingPartyCooperationAgency: 'Processing party (cooperative organization)',
    agencyIntentionList: 'Institutional Intent Business List',
    applicationType: 'application type',
    operation: 'operation',
    notPassing: 'Do not pass',
    passed: 'has passed',
    rejected: 'Rejected',
    cooperationAgencyRequest: 'Cooperative agency request',
    initiatorCooperationAgency: 'Initiator (cooperative agency)',
    processingPartyEnterpriseName: 'Processing party (company name)',
    associatedTime: 'association time',
    releaseTime: 'release time',
    validateInterger: 'can only be a number',
    validateSpecialChars: 'Cannot contain special characters or spaces',
    validateCreditCode: 'can only be numbers or letters',
    sessionRules: "can't exceed 100 characters",
    unifiedSocialCreditCodeRules: "Can't exceed 18 characters",
    cooperationAgencyCodeRules: "Can't exceed 32 characters",
    pleaseSelectData: 'Please select data',
    applicationStatusA: 'Enterprise application to join the partner institution',
    applicationStatusB: 'Enterprise exits partner',
    applicationStatusC: 'The partner institution invites the company',
    applicationStatusD: 'Partnership to create a business',
    applicationStatusE: 'Cooperative organization deletes the enterprise',

    adminViewHistoryOwnershipInfo: 'Administrator view historical attribution information',
    personalName: 'personal name',
    ownershipType: 'home type',
    pleaseChoose: 'Please select',
    levelNameTips: 'The current number of companies has no indicators',
    name: 'name',
    ownershipTime: 'Home time',
    personalJoinEnterprise: 'Personal joins the company',
    enterpriseInvitePersonal: 'Business invites individuals',
    personalCreateEnterprise: 'Personal creation of business',
    enterpriseCreatePersonal: 'Enterprise create a personal',

    enterpriseOwnershipAgency: 'Corporate Ownership Management',
    cooperationAgencyType: 'Cooperative organization type',
    sendQuery: 'send request',
    receiveQuery: 'receive request',
    applyRecord: 'Request feedback record',
    release: 'release',
    hasBeenSent: 'sent',
    repeal: 'Undo',
    sendRequest: 'send request',
    releaseTips: 'Are you sure to cancel the affiliation with the agency? ',
    prompt: 'prompt',
    confirm: 'OK',
    cancel: 'Cancel',
    releaseSuccess: 'Unsuccessful',
    repealTips: 'Are you sure to revoke? ',
    repealSuccess: 'Undo successfully',
    receiveQueryTips: '*This session can only accept invitations from one institution',
    invitationTime: 'Invitation time',
    accept: 'Accept',
    notAccepted: 'Do not accept',
    accepted: 'Accepted',
    agencyAcceptTips: 'Can only accept an invitation from an organization, is it accepted? ',
    acceptSuccess: 'Accept invitation successfully',
    acceptError: 'already associated data',
    reviewTime: 'Audit time',
    agencyName: 'institution name',
    auditStatus: 'Audit status',

    enterpriseOwnershipManagement: 'Enterprise affiliation management',
    identityNumber: 'ID number',
    mailbox: 'mailbox',
    cellphoneNumber: 'Mobile number',
    sendRequestToPersonalUser: 'Request a request to an individual user',
    sendInvitation: 'send invitation',
    subPersonalManagement: 'Subordinate personal management',
    contactNumber: 'contact phone',
    delete: 'delete',
    reviewIndividualUserApplication: "Review individual user's application",
    applicant: 'applicant',
    applicationTime: 'application time',
    examinationPassed: 'Audit passed',
    personalReviewResultsFeedback: 'Personal Review Result Feedback',
    reviewerPersonalUserName: '(auditor) individual user name',
    phoneNumberRules: "Can't exceed 11 characters",
    underReview: 'under review',
    deleteTips: 'Are you sure to delete? ',
    deleteSuccess: 'delete successfully',
    agencyRelatedEnterpriseMgt: 'Institutional Associated Enterprise Management',
    createEnterpriseUser: 'Create a business user',
    applicationResultFeedback: 'application result feedback',
    reviewerEnterpriseName: '(auditor) business name',
    subEnterpriseManagement: 'Subordinate Enterprise Management',
    sendInvitationSuccess: 'Send invitation success',
    personalOwnershipMgt: 'Personal affiliation management',
    applyJoinEnterprise: 'Apply to join the company',
    location: 'location',
    ownershipEstablishment: 'Home establishment',
    alreadyApplied: 'Approved',
    reviewEnterpriseRequest: "A review of the company's request",
    reviewEnterpriseRequestTableTips: '*This session can only accept invitations from one company',
    review: 'Audit',
    agree: 'Agree',
    reject: 'reject',
    reviewResultsFeedback: 'audit result feedback',
    releaseTipsB: 'Are you sure to release the relationship with the company? ',
    enterpriseAcceptTips: 'When the world can only accept an invitation from a company, is it accepted? ',
    enterpriseAcceptSuccess: 'Already invited'
  },
  //工作流
  Workflow: {
    publish: 'deploy',
    flowModel: 'process template',
    modelName: 'template name',
    childSys: 'subsystem',
    deployState: 'template status',
    published: 'deployed',
    unpublish: 'undeployed',
    confirmWarn: 'This will delete the process template. Do you want to continue?',
    inputFlowName: 'Please enter a process template name',
    processTitle: 'Process definition',
    processName: 'process name',
    processKey: 'process primary key',
    suspensionState: 'status',
    deployUser: 'deployer',
    deployDate: 'deploy time',
    version: 'version',
    activation: 'activation',
    suspend: 'suspend',
    processDelete: 'This action will delete the process definition and continue ?'
  }
};

// 声明全局变量
kindo.langen = language;

export { language };
